### ISSUE TITLE
Output of formatR has a trailing whitespace

### ISSUE THREAD

**Issue by mr-karan** [yihui/formatR#49]
While using formatR from the terminal, I noticed that the output has an extra space at the last line of the output. Shouldn't be there. 

Steps to reproduce:

`Rscript -e 'library(formatR)' -e 'formatR::tidy_source({{filename.R}})'`

**Comment by yihui** [comment]
Nice observation. Fixed now. Thanks!

**Comment by sils1297** [comment]
Hey @yihui thanks for the super fast fix! Would you mind giving us a ping when this gets released?

Background: we just integrated formatR into coala (coala-analyzer.org) so it can be used via various interfaces, editor plugins and even to automatically review github pull requests. We had to make a small workaround because of that issue which we'd love to remove :)

**Comment by yihui** [comment]
Unfortunately I just removed formatR to CRAN the other day, so the next release will have to wait for at least a week. Before the next release, I believe you can use this workaround:

```r
cat(formatR::tidy_source("filename.R")$text.tidy, sep = "\n")
```

**Comment by sils1297** [comment]
no problem, we already have a workaround. I'm just asking for a ping ;)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-08 17:58 GMT+01:00 Yihui Xie <notifications@github.com>:

**Comment by sils1297** [comment]
/me would love it if GitHub had a subscribe button on the releases page
