### ISSUE TITLE
formatR and testthat 

### ISSUE THREAD

**Issue by edlee123** [yihui/formatR#55]
Copy to clipboard:

```
test_that("formatR can format a test",{

  val1 <- 1
  val2 <- 1
  expect_equal(val1,  val2)
})
```

```
> tidy_source()
Error in parse(text = lines, keep.source = TRUE) : 
  <text>:6:0: unexpected end of input
4:   val2 <- 1
5:   expect_equal(val1,  val2)
```
Similarly:
```
test_that("formatR can format a test",{
  val1 <- 1
  val2 <- 1
  expect_equal(val1,  val2)

})
```
```
> tidy_source()
Error in parse(text = lines, keep.source = TRUE) : 
  <text>:6:0: unexpected end of input
4:   expect_equal(val1,  val2)
5: 
  ^
```
This is ok:
```
test_that("formatR can format a test",
{
  val1 <- 1
  val2 <- 1
  expect_equal(val1,  val2)
}
)
```
```
> tidy_source()
test_that("formatR can format a test", {
    val1 <- 1
    val2 <- 1
    expect_equal(val1, val2)
})
```

**Comment by yihui** [comment]
Just make sure you fully copy the last line -- the final EOL should also be copied, otherwise R may have problems with reading the last line, hence the R code is incomplete.

This may not be okay:

<img width="328" alt="screen shot 2016-07-07 at 3 07 27 am" src="https://cloud.githubusercontent.com/assets/163582/16646493/039554f6-43f0-11e6-98d4-7fa69303fbdc.png">

This is okay:

<img width="321" alt="screen shot 2016-07-07 at 3 07 45 am" src="https://cloud.githubusercontent.com/assets/163582/16646494/039620c0-43f0-11e6-8045-2da023881c1f.png">
